### ISSUE TITLE
Names

### ISSUE THREAD

**Issue by Daniel15** [ien646/gamma-icc#1]
Thanks for this!

Is it possible to give these profiles unique names so they appear like "DisplayCAL sRGB 0.8 gamma" (for example) instead of all appearing as "DisplayCAL calibration preset: sRGB"? It's hard to tell which one is which in the "Assign Profile" list in KDE:

![image](https://github.com/ien646/gamma-icc/assets/91933/1168e40d-29d2-4aeb-9f4f-571e9cea504a)

**Comment by ien646** [comment]
Seems like it's using the description field to display that name. However, the field seems to be length coded at the beginning of the .icc file. I've tried extracting and modifying the .cal file with iccvcgt, but when generating the new .icc, the description field is ignored and the original from the source .icc is used instead.

Try this:
```bash
# Remove one '-' at the end if using 2 digits right of the decimal point (i.e. 0.85)
sed -i -e 's/DisplayCAL calibration preset: sRGB/DisplayCAL sRGB 0.8 gamma----------/g' sRGB-0.8.icc
```

If this works, I might replace the ICCs later.
